name: test-bot
on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ '3.10' ]
        browser: [ 'chrome' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pwdriver
          pip install -r requirements.txt
      - name: Install chrome
        uses: nanasess/setup-chromedriver@v1.0.7
        if: |
          matrix.browser == 'chrome'
      - name: Start XVFB and setup chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        if: |
          matrix.os != 'windows-latest' && matrix.browser == 'chrome'
      - name: Setup chromedriver
        run: chromedriver --url-base=/wd/hub &
        if: |
          matrix.os == 'windows-latest' && matrix.browser == 'chrome'
      - name: Test in ${{ matrix.browser }} with unittest
        run: python -m unittest tests/${{ matrix.browser }}.py
