name: test-bot
on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  test:
    name: ${{ matrix.browser }} e2e test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ '3.10' ]
        browser: [ 'chrome', 'edge', 'safari' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pwdriver codecov
      - name: Install chrome
        uses: nanasess/setup-chromedriver@v1.0.7
        if: matrix.browser == 'chrome'
      - name: Setup chromedriver
        run: chromedriver --url-base=/wd/hub &
        if: matrix.browser == 'chrome'
      - name: Install edge
        uses: browser-actions/setup-edge@latest
        if: matrix.os != 'ubuntu-latest' && matrix.browser == 'edge'
      - name: Start XVFB
        run: Xvfb :99 &
        if: matrix.os != 'windows-latest'
      - name: Test in ${{ matrix.browser }} with unittest
        run: coverage run --omit="tests/*" -m unittest discover tests/ ${{ matrix.browser }}.py
        env:
          DISPLAY: :99
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: coverage.xml
  coverage:
    name: coverage upload
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1