name: test-bot
on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  test:
    name: ${{ matrix.browser }} e2e test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ '3.10' ]
        browser: [ 'chrome', 'edge', 'safari' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pwdriver codecov
      - name: Install chrome
        if: matrix.browser == 'chrome'
        uses: nanasess/setup-chromedriver@v1.0.7
      - name: Setup chromedriver
        if: matrix.browser == 'chrome'
        run: chromedriver --url-base=/wd/hub &
      - name: Install edge
        if: runner.os != 'Linux' && matrix.browser == 'edge'
        uses: browser-actions/setup-edge@latest
      - name: Start XVFB
        if: runner.os != 'Windows'
        run: Xvfb :99 &
      - name: Make configuration file
        run: |
          echo [automation] > config.ini
          echo automation.browser=${{ matrix.browser }} >> config.ini
          echo automation.local=true >> config.ini
          echo automation.url=http://localhost:4444/wd/hub >> config.ini
      - name: Test in ${{ matrix.browser }} with unittest
        if: runner.os != 'macOS' && matrix.browser == 'safari'
        run: coverage run --omit="tests/*" -m unittest discover tests/ eventdriver.py
        env:
          DISPLAY: :99
      - name: Upload coverage
        uses: codecov/codecov-action@v3